<?php 
class idiomas{
	function español(){
$arrays=array(
	"Usuario"=>"Usuario" ,
	"Volver"=>"Volver",
	"Funcionalidad creada correctamente"=>"Funcionalidad creada correctamente",
	"Datosmonitor"=>"Datos del monitor",
	"Datosdeportista"=>"Datos del Deportista",
	"Password"=>"Contraseña",
	"Funcio"=>"Funcionalidad",
	"Grupo"=>"Gestion de Grupo",
	"GrupoName"=>"Grupo",
	"FechaNac"=>"Fecha  de Nacimiento",
	"Nombre"=>"Nombre",
	"descripcion" => "Descripción",
	"Usuarionuevo"=>"Usuario que desea modificar",
	"nombreNuevo"=>"Nuevo Nombre",
	"Eliminado"=>"Imposible Eliminar",
	"Funcionalidad"=>"Gestion de Funcionalidades",
	"Apellidos"=>"Apellidos",
	"USUARIOSINCORRECTO"=>"Introduce otro Usuario o DNI",
	"EliminacionExito"=>"Eliminado con Exito",
	"Apellido1"=>"Apellido1",
	"Apellido2"=>"Apellido2",
	"Telefono"=>"Telefono",
	"email"=>"Email del Usuario",
	"modificado"=>"No hay ese nombre para modificar",
	"DNI"=>"DNI",
	"TIPO"=>"Tipo",
	"BajaFuncionalidad"=>"Baja de Funcionalidad",
	"ModificarFuncionalidad"=>"Modificar Funcionalidad",
	"ConsultarFuncionalidad"=>"Consultar Funcionalidad",
	"ConsultarGrupo"=>"Consultar Grupo",
	"BajaGrupo"=>"Baja de Grupo",
	"ModificarGrupo"=>"Modificar Grupo",
	"AltaGrupo"=>"Alta de Grupo",
	"Menu"=>"Menu Principal",
	"IntroduccionErronea"=>"Por favor Introduzca otro nombre",
	"GestionUsuarios"=>"Gestion de Usuarios",
	"GestionDeportista"=>"Gestion de Deportistas",
	"GestionMonitores"=>"Gestion de Monitores",
	"GestionActividades"=>"Gestion de Actividades",
	"GestionNotificaciones"=>"Gestion de Notificaciones",
	"GestionSesiones"=>"Gestion de Sesiones",
	"GestionReservas"=>"Gestion de Reservas",
	"GestionTablas"=>"Gestion de Tablas",
	"Reset"=>"Reset",
	"AltaFuncionalidad"=>"Alta Funcionalidad",
	"AltaUsuario"=>"Alta de Usuario",
	"BajaUsuario"=>"Baja de Usuario",
	"ModificacionUsuario"=>"Modificacion de Usuario",
	"ConsultaUsaurio"=>"Consultar Usuario",
	"Altarealizada"=>"Insercion Realizada",
	"Altaerronea"=>"Rellene los campos necesarios");

return $arrays;
}
function gallego(){

$arrays=array(
	"Usuario"=>"Usuario" ,
	"Usuarionuevo"=>"Usuario que desexa modificar",
	"Datosmonitor"=>"Datos do monitor",
	"Funcionalidad"=>"Xestion de Funcionalidades",
	"GestionUsuarios"=>"Xestion de Usuarios",
	"Grupo"=>"Xestion de Grupo",
	"GrupoName"=>"Grupo",
	"AltaFuncionalidad"=>"Alta Funcionalidad",
	"USUARIOSINCORRECTO"=>"Introduce outro Usuario ou DNI",
	"ModificarFuncionalidad"=>"Modificar Funcionalidade",
	"BajaFuncionalidad"=>"Baixa de Funcionalidade",
	"ConsultarFuncionalidad"=>"Consultar Funcionalidade",
	"ConsultarGrupo"=>"Consultar Grupo",
	"BajaGrupo"=>"Baixa de Grupo",
	"ModificarGrupo"=>"Modificar Grupo",
	"AltaGrupo"=>"Alta de Grupo",
	"Funcio"=>"Funcionalidad",
	"Eliminado"=>"Imposible Eliminar",
	"EliminacionExito"=>"Eliminado con Exito",
	"modificado"=>"Non  existe ese nome para modificar",
	"Datosdeportista"=>"Datos do Deportista",
	"Password"=>"Contrasinal",
	"FechaNac"=>"Data de Nacimiento",
	"IntroduccionErronea"=>"Por favor Introduzca outro nome",
	"Nombre"=>"Nome",
	"nombreNuevo"=>"Novo Nome",
	"Apellidos"=>"Apelidos",
	"Apellido1"=>"Apelido1",
	"Apellido2"=>"Apellido2",
	"Telefono"=>"Telefono",
	"email"=>"Email do Usuario",
	"DNI"=>"DNI",
	"TIPO"=>"Tipo",
	"Menu"=>"Menu Principal",
	"GestionUsuarios"=>"Xestion de Usuarios",
	"GestionDeportista"=>"Xestion de Deportistas",
	"GestionMonitores"=>"Xestion de Monitores",
	"GestionActividades"=>"Xestion de Actividades",
	"GestionNotificaciones"=>"Xestion de Notificacions",
	"GestionSesiones"=>"Xestion de Sesiones",
	"GestionReservas"=>"Xestion de Reservas",
	"GestionTablas"=>"Xestion de Tablas",
	"Reset"=>"Rest",
	"Altarealizada"=>"Insercion Realizada",
	"AltaUsuario"=>"Alta de Usuario",
	"BajaUsuario"=>"Baixa de Usuario",
	"ModificacionUsuario"=>"Modificacion de Usuario",
	"ConsultaUsaurio"=>"Consultar Usuario",
	"Altaerronea"=>"Enche os campos necesarios");

return $arrays;

}

function ingles(){

$arrays=array(
	"Usuario"=>"User",
	"Usuarionuevo"=>"Update this User",
	"Password"=>"Password",
	"AltaFuncionalidad"=>"Create Features",
	"Grupo"=>"Group Management",
	"GrupoName"=>"Group",
	"BajaFuncionalidad"=>"Delete Features",
	"Funcionalidad"=>"Features Management",
	"ConsultarGrupo"=>"Search Group",
	"BajaGrupo"=>"Delete Group",
	"ModificarGrupo"=>"Update Group",
	"AltaGrupo"=>"Create Group",
	"Eliminado"=>"Delete Imposible",
	"EliminacionExito"=>"Succes Deleted",
	"modificado"=>"Imposible EDIT",
	"USUARIOSINCORRECTO"=>"Insert another User or DNI",
	"ConsultarFuncionalidad"=>"Search Features",
	"ModificarFuncionalidad"=>"Update Features",
	"Datosmonitor"=>"Coach Data",
	"Funcio"=>"Feature",
	"Datosdeportista"=>"Athlete data",
	"GestionUsuarios"=>"Users Management",
	"IntroduccionErronea"=>"Please insert another name",
	"FechaNac"=>"Birthdate",
	"Nombre"=>"Name",
	"nombreNuevo"=>"New Name",
	"Apellidos"=>"LastName",
	"Apellido1"=>"LastName1",
	"Apellido2"=>"LastName2",
	"Telefono"=>"Phone",
	"email"=>"Email",
	"DNI"=>"DNI",
	"TIPO"=>"Tipe",
	"Menu"=>"Main menu",
	"GestionUsuarios"=>"Users Managment",
	"GestionDeportista"=>"Athlete Management",
	"GestionMonitores"=>"Monitors Management ",
	"GestionActividades"=>"Activities Management",
	"GestionNotificaciones"=>"Reports Management ",
	"GestionSesiones"=>"Session Management",
	"GestionReservas"=>"Reservs Management ",
	"GestionTablas"=>"Tables Management",
	"Reset"=>"Rest",
	"Altarealizada"=>"Insercion Realizada",
	"AltaUsuario"=>"Create User",
	"BajaUsuario"=>"Delete User",
	"ModificacionUsuario"=>"Update User",
	"ConsultaUsaurio"=>"Search User",
	"Altaerronea"=>"Rellene los campos necesarios");

return $arrays;

}

}

?>